### ISSUE TITLE
Add support for PKCS#12-formatted certificates 

### ISSUE THREAD

**Issue by nethraravindran** [IBM-Swift/Kitura-NIO#14]
SSL verification fails when we create `SSLConfig` with pfx certificates. 
*Note*: Swift nio-ssl doesn't support PKCS#12-formatted certificates

**Comment by pushkarnk** [comment]
https://github.com/apple/swift-nio-ssl/issues/17

**Comment by nethraravindran** [comment]
PR: https://github.com/IBM-Swift/Kitura-NIO/pull/58

**Comment by pushkarnk** [comment]
Thanks for your work on this, @nethraravindran !
