### ISSUE TITLE
Building/testing against swift-nio's master 

### ISSUE THREAD

**Issue by pushkarnk** [IBM-Swift/Kitura-NIO#150]

**Comment by pushkarnk** [comment]
Pushed a branch with some changes that ensure a successful build: https://github.com/IBM-Swift/Kitura-NIO/tree/development

**Comment by pushkarnk** [comment]
https://travis-ci.org/IBM-Swift/Kitura-NIO/builds/481256915

**Comment by pushkarnk** [comment]
I see performance of plaintext and json benchmarks going down with Swift 5 / NIO2

**plaintext**

Client threads | 1.0.14 | Swift5-1.0.14 | Swift5(NIO master)
-- | -- | -- | --
256 | 14.77 | 13.74 | 13.77
1024 | 14.76 | 13.37 | 13.04
4096 | 14.25 | 12.7 | 12.73
16384 | 13.79 | 12.51 | 12.44

**json**

Client threads | 1.0.14 | Swift5(1.0.14) | Swift5(NIO master)
-- | -- | -- | --
8 | 6.94 | 6.35 | 6.42
16 | 9.17 | 8.42 | 8.53
32 | 10.95 | 10.21 | 10.32
64 | 11.58 | 10.71 | 10.83
128 | 11.8 | 10.94 | 11.14
256 | 11.91 | 11.01 | 11.25

**Comment by weissi** [comment]
@pushkarnk please note that we haven't started optimising for Swift 5 yet and there's quite a few things where Swift 5 fastpaths aren't correctly hit yet, like:

- https://bugs.swift.org/browse/SR-9700
- https://bugs.swift.org/browse/SR-9604

So it's not too surprising that things are a big slower right now. If you do manage to pinpoint a particular slowdown in NIO with Swift 5, we'd love to hear, then we can further analyse and fix/file bugs.

**Comment by pushkarnk** [comment]
Database perf tests

**db** (Swift 5 shows a dip by up to 9%)

Client threads | 1.0.14 | Swift5(1.0.14) | Swift5(NIO master)
-- | -- | -- | --
8 | 3.36 | 3.24 | 3.23
16 | 5.34 | 5.09 | 5.11
32 | 5.69 | 5.34 | 5.35
64 | 5.71 | 5.37 | 5.33
128 | 5.58 | 5.3 | 5.29
256 | 5.56 | 5.31 | 5.29


**Updates** (perf down by up to 7%)

Num queries | 1.0.14 | Swift5(1.0.14) | Swift5(NIO master)
-- | -- | -- | --
1 | 3.5 | 3.24 | 3.26
5 | 1.83 | 1.74 | 1.74
10 | 1.46 | 1.4 | 1.41
15 | 1.32 | 1.28 | 1.28
25 | 1.22 | 1.18 | 1.18

**Queries** (perf down by up to 9%)

Num queries | 1.0.14 | Swift5(1.0.14) | Swift5(NIO master)
-- | -- | -- | --
1 | 4.58 | 4.13 | 4.15
5 | 2.91 | 2.73 | 2.74
10 | 2.4 | 2.28 | 2.29
15 | 2.24 | 2.13 | 2.15
20 | 2.15 | 2.06 | 2.07
25 | 2.1 | 2.02 | 2.02

**Comment by pushkarnk** [comment]
Did a comparison of flamegprahs collected against `plaintext` on `1.0.14` and `Swift 5-NIO2`. 

It is the `NSString` methods that seem to be bringing down performance. Especially:
`NSString.substring(with:)` -  3 times more CPU spent (0.5% in 4.2.1 vs. 1.5% in 5)
`NSString.getCharacters(_:range)` - 2 times more CPU spent (0.17% in 4.2.1 vs. 0.35% in 5)

**Comment by pushkarnk** [comment]
Closing this. I've opened #170 to deal with the performance aspects.
