### ISSUE TITLE
SwiftMetrics builds with Kitura-NIO are failing

### ISSUE THREAD

**Issue by ianpartridge** [IBM-Swift/Kitura-NIO#180]
https://travis-ci.org/RuntimeTools/SwiftMetrics/builds/505750620

**Comment by ianpartridge** [comment]
See also https://travis-ci.org/IBM-Swift/Kitura-Sample/jobs/505676238 which looks like the same problem.

**Comment by pushkarnk** [comment]
@ianpartridge  Sincere apologies. I prematurely tagged Kitura-NIO with some changes meant for WebSocket compression. I've deleted the tag now. Can you please re-trigger the SwiftMetrics builds? The Kitura-Sample builds seem to be passing.

**Comment by ianpartridge** [comment]
Thanks, I've restarted the SwiftMetrics jobs which failed.

**Comment by ianpartridge** [comment]
Builds have passed - thanks.
