### ISSUE TITLE
Feature Request: access to EventLoopGroup

### ISSUE THREAD

**Issue by mlilback** [IBM-Swift/Kitura-NIO#224]
According to documentation, an application should generally have a single EventLoopGroup. Kitura-NIO create its own group and threads, and provides no access. Performance will suffer if every library used creates its own group.

I'd like the options:
1. To create my own group, and pass it into Kitura. 
2. If a group is not specified and Kitura creates one, n accessor to get that group.

**Comment by weissi** [comment]
I agree, especially option 1 sounds like a good plan to me. In `async-http-client` for example there’s the [`EventLoopGroupProvider`](https://github.com/swift-server/async-http-client/blob/master/Sources/AsyncHTTPClient/HTTPClient.swift#L57) type to do this.

**Comment by pushkarnk** [comment]
Sounds reasonable to me. We'd be deviating from the `Kitura-net` API, but I assume that developers who want to use NIO's types may not really consider switching over to `Kitura-net`.

Your thoughts @djones6 ?

**Comment by djones6** [comment]
I think that deviation from Kitura-net is okay in this instance.  As long as the expectation is clear that the application is then tightly coupled to Kitura-NIO, I don't see a problem with providing additional features such as this.

**Comment by harish1992** [comment]
Hi @mlilback, PR #225 adds this feature.
