### ISSUE TITLE
Consider adding TSan to the tests runner on 5.1

### ISSUE THREAD

**Issue by weissi** [IBM-Swift/Kitura-NIO#228]
Swift 5.1 on Linux now supports Thread Sanitizer (TSan). I think Kitura-NIO (and really all Kitura projects) should strongly consider adding `--sanitize=thread` to the `SWIFT_TEST_ARGS`. I see no downside in doing that.

<img width="1006" alt="Screenshot 2019-10-17 at 11 45 52 am" src="https://user-images.githubusercontent.com/624238/67038154-bbbcf780-f0d3-11e9-83aa-b19ce32c0a0b.png">

**Comment by harish1992** [comment]
Added in PR #230.
