### ISSUE TITLE
testRedirect in Kitura fails with latest Kitura-NIO

### ISSUE THREAD

**Issue by nethraravindran** [IBM-Swift/Kitura-NIO#59]

**Comment by pushkarnk** [comment]
Looks like a regression caused by #54

**Comment by pushkarnk** [comment]
@saiHemak

**Comment by saiHemak** [comment]
@pushkarnk  Sure will look in to it

**Comment by saiHemak** [comment]
@pushkarnk / @nethraravindran I tried to recreate the issue by following these steps : 
1. Cloned the Kitura repository and checked out kitura-2.4-nio
2.Ran TestResponse.testRedirect and it failed with/without fix

**Comment by saiHemak** [comment]
The test case  is pointing to ibm.com site which started behaving differently due to which the body length is 0. The dependency to the external URL has been removed in Kitura Tests and after rebasing the problem is no longer seen with Kitura-NIO too
