### ISSUE TITLE
Linker error in libz on Ubuntu 16.04

### ISSUE THREAD

**Issue by nethraravindran** [IBM-Swift/Kitura-NIO#62]
```
Linking ./.build/x86_64-unknown-linux/debug/KituraPackageTests.xctest
/root/Kitura/.build/x86_64-unknown-linux/debug/NIOHTTP1.build/HTTPResponseCompressor.swift.o:/root/Kitura/.build/x86_64-unknown-linux/debug/NIOHTTP1.build/HTTPResponseCompressor.swift.o:function _T08NIOHTTP122HTTPResponseCompressorC19deinitializeEncoder33_E8A369BA8CC72FD6D05117C456504CA2LLyyF: error: undefined reference to 'deflateEnd'
/root/Kitura/.build/x86_64-unknown-linux/debug/NIOHTTP1.build/HTTPResponseCompressor.swift.o:/root/Kitura/.build/x86_64-unknown-linux/debug/NIOHTTP1.build/HTTPResponseCompressor.swift.o:function _T08NIOHTTP119PartialHTTPResponse33_E8A369BA8CC72FD6D05117C456504CA2LLV12compressBody3NIO10ByteBufferVSgSC10z_stream_sVz10compressor_AF0oP9AllocatorV9allocators5Int32V4flagtF: error: undefined reference to 'deflateBound'
/root/Kitura/.build/x86_64-unknown-linux/debug/NIOHTTP1.build/HTTPResponseCompressor.swift.o:/root/Kitura/.build/x86_64-unknown-linux/debug/NIOHTTP1.build/HTTPResponseCompressor.swift.o:function _T0SC10z_stream_sV8NIOHTTP1E15deflateToBuffer33_E8A369BA8CC72FD6D05117C456504CA2LLs5Int32V3NIO04ByteE0Vz6buffer_AG4flagtFSis016UnsafeMutableRawE7PointerVcfU_: error: undefined reference to 'deflate'
/root/Kitura/.build/x86_64-unknown-linux/debug/NIOHTTP1.build/HTTPResponseCompressor.swift.o:/root/Kitura/.build/x86_64-unknown-linux/debug/NIOHTTP1.build/HTTPResponseCompressor.swift.o:function CNIOZlib_deflateInit2: error: undefined reference to 'deflateInit2_'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
<unknown>:0: error: link command failed with exit code 1 (use -v to see invocation)
```

`swift test -Xlinker -lz` is used as a temporary work-around for the above issue.

**Comment by pushkarnk** [comment]
@nethraravindran Does this happen on both 14.04 and 16.04?

**Comment by nethraravindran** [comment]
@pushkarnk No, this doesn't happen on 14.04

**Comment by pushkarnk** [comment]
A found a handful of projects/forums in which this problem was discussed:

https://elixirforum.com/t/ubuntu-exec-erlexec-not-found/10499/6
https://github.com/arybczak/ncmpcpp/issues/138
https://github.com/TrinityCore/TrinityCore/issues/19074
https://github.com/grpc/grpc/issues/11768

All of them talk about solving the problem using `-lz` but there's no drill-down into why this problem didn't show up on Ubuntu 14.04.

On Ubuntu 16.04, I ran `ldconfig` and I can see libz present in the search path:
```
ldconfig -v | grep "libz"
	libz.so.1 -> libz.so.1.2.8
```

**Comment by ianpartridge** [comment]
Does the linking still fail if we add `CNIOZlib` to the dependencies of the [KituraNet target](https://github.com/IBM-Swift/Kitura-NIO/blob/821f3862042543efd8c0f3015fec020d11c52527/Package.swift#L41)?

**Comment by weissi** [comment]
That sounds to me like either `zlib` or `pkg-config` isn't installed. You can test this by running

    pkg-config --libs zlib

which should output

    -lz

Or (on Debian systems) you should be able to see if zlib is installed with development headers like this

    dpkg -l zlib1g-dev

**Comment by pushkarnk** [comment]
And I can see that the `trusty` images (Ubuntu 14.04) have `pkg-config` pre-installed.

**Comment by pushkarnk** [comment]
@nethraravindran Can we try adding `pkg-config` to the `apt-get install .... ` list in [build.sh](
https://github.com/IBM-Swift/Kitura-NIO/blob/master/build.sh)

**Comment by nethraravindran** [comment]
@pushkarnk Sure! Have created the PR :[https://github.com/IBM-Swift/Kitura-NIO/pull/77](url)

**Comment by nethraravindran** [comment]
PR merged. Closing this issue.
