### ISSUE TITLE
ThinkTime test route /think/async fails with KituraNIO

### ISSUE THREAD

**Issue by nethraravindran** [IBM-Swift/Kitura-NIO#63]
ThinkTime test with the route `/think/async` crashes in Kitura-NIO. 

The crash is because the thread that initiated the I/O task is not the same thread that performs the I/O operation.  ie, the current thread that tries to perform the operation is not as the same thread that was tied with EventLoop. 

Hence we must ensure that we perform the I/O task on the same thread or we submit the task to be executed to the EventLoop.

**Comment by nethraravindran** [comment]
PR : https://github.com/IBM-Swift/Kitura-NIO/pull/64

**Comment by pushkarnk** [comment]
@nethraravindran Can you provide a description of the bug please?

**Comment by pushkarnk** [comment]
#64 merged. Thanks @nethraravindran
