### ISSUE TITLE
Kitura tests on kitura-nio branch leak the MultiThreadedEventLoopGroup threads

### ISSUE THREAD

**Issue by weissi** [IBM-Swift/Kitura-NIO#67]
This might really be a kitura issue but it probably also happens here: Kitura tests on kitura-nio branch leak the MultiThreadedEventLoopGroup threads, basically the `MultiThreadedEventLoopGroup` that are created in the tests are never torn down, ie. the threads are still kept alive.

Essentially it's the [same issue that Vapor has too](https://github.com/vapor/vapor/issues/1778)

[`MultiThreadedEventLoopGroup.syncShutdownGracefully`](https://apple.github.io/swift-nio/docs/current/NIO/Classes/MultiThreadedEventLoopGroup.html#/s:3NIO14EventLoopGroupP18shutdownGracefullyy8Dispatch0G5QueueC5queue_ys5Error_pSgctF) should be used for example in the `tearDown` method of a test

**Comment by nethraravindran** [comment]
@pushkarnk I guess we are already doing that https://github.com/IBM-Swift/Kitura-NIO/blob/106677541e0bcd13c3a631db15427e1e8c614235/Sources/KituraNet/HTTP/HTTPServer.swift#L222 here.

**Comment by weissi** [comment]
@pushkarnk/@nethraravindran I think it might be the one from `ClientRequest`.

**Comment by nethraravindran** [comment]
@weissi Thank you for your input. Yes it is from `ClientRequest`.  Now, with `syncShutdownGracefully` in ClientRequest I see a very minimal leak :)

**Comment by nethraravindran** [comment]
PR https://github.com/IBM-Swift/Kitura-NIO/pull/76

@weissi  Thanks! With this fix, I see no leak :)

**Comment by weissi** [comment]
awesome, thanks 👍. I'm going to close this
